name: tekartik_platform_io
description: Platform io
version: 0.3.0
publish_to: none

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  path: '>1.4.0'
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform
      ref: dart2
    version: '>=0.2.1'
  process_run: '>=0.10.0+1'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  tekartik_platform_test:
    path: ../platform_test
  build_runner: any
  build_test: any
dependency_overrides:
  tekartik_platform:
    path: ../platform