name: tekartik_platform_test
description: Platform test
version: 0.2.1
publish_to: none

environment:
  sdk: '>=2.12.0-259.14.beta <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: null_safety
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform
      ref: null_safety
    version: '>=0.2.1'

dev_dependencies:
  build_runner: ">=0.8.8"
  build_test: ">=0.10.2"
  test: ">=1.2.0"
  dev_test: any
  process_run: '>=0.10.0+1'

dependency_overrides:
  tekartik_platform:
    path: ../platform